### ISSUE TITLE
Followed NodeJS Tutorial on Amazon ELB, but when trying to upload application this happened:

### ISSUE THREAD

**Issue by UltimateCodeWarrior** [aws-samples/eb-node-express-sample#5]
2016-11-29 21:26:00 UTC-0700	ERROR	Failed to deploy application.
2016-11-29 21:26:00 UTC-0700	ERROR	Auto Scaling LowerThreshold setting cannot be applied because AWSEBCloudwatchAlarmLow doesn't exist.
2016-11-29 21:26:00 UTC-0700	ERROR	"option_settings" in one of the configuration files failed validation. More details to follow.
2016-11-29 21:25:56 UTC-0700	INFO	Environment update is starting.
2016-11-29 21:23:56 UTC-0700	ERROR	Failed to deploy application.

**Comment by abhiksingh** [comment]
Did you deploy the application to a single instance environment? If you'd like to use this sample with a single instance environment, you can remove the aws:autoscaling:trigger section in the .ebextensions/options.config file.

**Comment by UltimateCodeWarrior** [comment]
Was following the tutorial here.   
https://aws.amazon.com/getting-started/projects/deploy-nodejs-web-app/

**Comment by Maker23** [comment]
The node.js getting started guide is still broken (one month later).   Here's the workaround:

After you "Create new environment" and before you upload and deploy the sample code, choose "Configuration" from the left-hand menus.  In the Scaling box click the little gear and change your environment type to **Load balancing, auto scaling**  (instead of single-instance).   Save changes, and choose "Dashboard" from the left-hand menus to get back to the screen where you can upload and deploy. 

Changing the environment is shown in the getting started guide in Step 5, [http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/GettingStarted.html#GettingStarted.Walkthrough.EditConfig](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/GettingStarted.html#GettingStarted.Walkthrough.EditConfig)

**Comment by nikhilnxvverma1** [comment]
Thanks Maker23. That helped. I am a new AWS user, and I am finding the documentation both outdated and horrible.

**Comment by abhiksingh** [comment]
Thanks for the feedback. The code has been fixed to enable deploying it to a single instance environment without errors.

**Comment by jonchurch** [comment]
Just ran into this same issue as OP, and resolved with @Maker23's suggestion

FYI I downloaded the project from https://github.com/awslabs/eb-node-express-sample/releases/download/v1.0/eb-node-express-sample-v1.0.zip and setup the EB instance myself, instead of following the preconfigured link that is present under step 2 [here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/GettingStarted.html) 

I recognize that link is preconfig'd with load-balancing turned on, but I avoided that intentionally to minimize the "magic". All the same, the code did not function under my single instance, and I had to manually switch to auto load balancing before getting a deploy to take.

**Comment by jhwheeler** [comment]
@abhiksingh I got the same issue as OP, and was resolved with @Maker23's suggestion as well. Also, side note: the docs are quite confusing and not very straightforward. A restructure, while time-consuming, would be highly beneficial for getting more developers to use the platform, and improve the general UX for all developers.

**Comment by cchang022477** [comment]
*sigh...* It is now July. I ran into the same issue and resolved by what @Maker23 suggested. Thanks @Marker23!

**Comment by mwunderl** [comment]
I've updated the link in the [tutorial](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/nodejs-dynamodb-tutorial.html) to point at the new [1.1 release](https://github.com/awslabs/eb-node-express-sample/releases/tag/v1.1). Both will now work with single instance environments.
